/* Optional actual-browser synthetic runtime test. Run: node --import tsx api/test/skill-runtime.browser.cjs
 * Keeps Chromium sandbox enabled. A launch denial is a blocker, never permission for --no-sandbox. */
const {chromium}=require('playwright-core');
const fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const {makeFixturePacks}=require('../src/skill/fixtures.ts'),{compileGuide}=require('../src/skill/compiler.ts'),{renderGuideHtml}=require('../src/skill/renderer.ts'); const html=renderGuideHtml(compileGuide(makeFixturePacks({destination:'Synthetic runtime test',departure:'',startDate:'2026-11-01',endDate:'2026-11-03',people:2,budget:10000,currency:'CNY',preferences:'',exclusions:''}),{mode:'fixture',sources:[],generatedAt:'2026-09-30T13:00:00Z'}));const server=http.createServer((q,r)=>{r.setHeader('content-type','text/html; charset=utf-8');r.end(q.url==='/preview' ? '<!doctype html><html><body><iframe title="Sandbox preview" sandbox="allow-scripts" style="width:100%;height:600px" srcdoc="'+html.replaceAll('&','&amp;').replaceAll('\"','&quot;').replaceAll('<','&lt;')+'"></iframe></body></html>' : html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',chromiumSandbox:true,args:['--disable-dev-shm-usage']});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Runtime error:',e.message)});const base='http://127.0.0.1:'+server.address().port;await page.goto(base);await page.waitForSelector('#adjust-timeline .card');
 const approved=await page.locator('#route').textContent();await page.getByLabel('第1站名称',{exact:true}).fill('更改合成地点用于测试');await page.getByLabel('第1站名称',{exact:true}).press('Tab');assert.match(await page.locator('#adjust-structured').inputValue(),/更改合成地点用于测试/);assert.equal(await page.locator('#route').textContent(),approved);
 await page.locator('#adjust-timeline').getByRole('button',{name:'↓ 下移',exact:true}).first().click();assert.match(await page.locator('#adjust-structured').inputValue(),/原地点ID/);await page.locator('#adjust-add').click();assert.equal(await page.locator('#adjust-timeline .card').count(),4);await page.locator('#adjust-restore').click();assert.equal(await page.locator('#adjust-timeline .card').count(),3);assert.equal(await page.locator('#adjust-structured').inputValue(),'');
 const second=await context.newPage();await second.goto(base);for(const p of [page,second]){await p.locator('.floating-trip').click();await p.locator('[data-trip-tab="ledger"]').click();}
 await page.locator('#ledger-note').fill('合成测试支出');await page.locator('#ledger-amount').fill('100.01');await page.locator('#ledger-save').click();assert.match(await page.locator('#ledger-balances').innerText(),/100.01/);assert.match(await page.locator('#ledger-balances').innerText(),/50.00/);assert.match(await page.locator('#ledger-balances').innerText(),/50.00/);
 await second.locator('#ledger-note').fill('另一窗口尚未保存');await second.locator('#ledger-amount').fill('20');await second.locator('#ledger-save').click();assert.match(await second.locator('#trip-runtime-status').innerText(),/另一窗口/);assert.equal(await second.locator('#ledger-note').inputValue(),'另一窗口尚未保存');assert.equal(await second.locator('#ledger-amount').inputValue(),'20');
 await page.locator('#ledger-balances').getByRole('button',{name:'已实际支付，登记',exact:true}).click();assert.match(await page.locator('#ledger-balances').innerText(),/消费总计 100.01/);await page.locator('#ledger-entries').getByRole('button',{name:'撤销还款记录',exact:true}).click();assert.match(await page.locator('#ledger-balances').innerText(),/应付 50.00/);
 await page.locator('#trip-mode [data-close]').click();await page.setViewportSize({width:320,height:800});console.log('Overflow diagnostics',await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1}).slice(0,8).map(e=>({tag:e.tagName,id:e.id,cls:e.className,right:e.getBoundingClientRect().right}))));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 const preview=await context.newPage();await preview.goto(base+'/preview');const frame=preview.frameLocator('iframe');await frame.locator('#adjust-timeline .card').first().waitFor({state:'visible'});assert.equal(await frame.locator('#adjust-timeline .card').count(),3);assert.match(await frame.locator('#runtime-status').innerText(),/无法永久保存/);
 for(const id of ['route','sights','shops','move','food','booking','words','tips']){await frame.locator('#contents a[href="#'+id+'"]').click();assert.equal(await frame.locator('.chapter[id]').count(),9);assert.equal(await frame.locator('html').evaluate(e=>e.ownerDocument.URL),'about:srcdoc');}
 await frame.locator('.floating-trip').click();assert.equal(await frame.locator('#trip-mode').evaluate(e=>e.open),true);await frame.locator('#trip-mode [data-close]').click();
 console.log('PASS sandbox srcdoc: all eight chapter links stay in the preview; trip mode still works');console.log('PASS actual Chromium: structured edit/reorder/add/restore preserve approved itinerary; integer-cent ledger and repayment reversal; stale cross-tab write rejected preserving input; mobile320 no overflow; zero runtime errors');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
