/** Trusted application code, never generated by the model. No fetch, eval, innerHTML or parent bridge. */
export const TRUSTED_RUNTIME = String.raw`(() => {
'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => Array.from(root.querySelectorAll(s));
// srcdoc inherits the host page URL: a native #chapter link can leave the
// sandboxed preview. Resolve and scroll inside this document instead.
$$('a[href^="#"]').forEach(link => link.addEventListener('click', event => {
  let id; try { id = decodeURIComponent(link.getAttribute('href').slice(1)); } catch { return; }
  const target = document.getElementById(id); if (!target) return;
  event.preventDefault(); target.scrollIntoView({ block: 'start' });
}));
const namespace = document.body.dataset.storage;
const message = (value) => { $$('#runtime-status,#trip-runtime-status').forEach(el => { el.textContent = value; }); };
const read = (key, fallback) => { try { const s = localStorage.getItem(namespace + ':' + key); return s ? JSON.parse(s) : fallback; } catch { message('此预览无法永久保存本地状态；下载 HTML 后在普通浏览器中打开可重试。'); return fallback; } };
const write = (key, value) => { try { localStorage.setItem(namespace + ':' + key, JSON.stringify(value)); return true; } catch { message('本地存储不可用或已满；本次修改仅保留在当前页面，请勿当作已同步。'); return false; } };
const openDialog = (dialog) => { if (dialog && !dialog.open) dialog.showModal(); };
$$('[data-close]').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
let day = 0, tab = 'itinerary';
function renderTrip() {
  $$('[data-day-panel]').forEach(el => { el.hidden = Number(el.dataset.dayPanel) !== day || el.dataset.panel !== tab; });
  $$('[data-select-day]').forEach(el => el.setAttribute('aria-pressed', String(Number(el.dataset.selectDay) === day)));
  $$('[data-trip-tab]').forEach(el => el.setAttribute('aria-selected', String(el.dataset.tripTab === tab)));
  $('#trip-day-label').textContent = '第 ' + (day + 1) + ' 天';
  $('#ledger-panel').hidden = tab !== 'ledger';
}
$$('[data-trip-open]').forEach(el => el.addEventListener('click', () => { if (el.dataset.tripOpen) day = Number(el.dataset.tripOpen); renderTrip(); openDialog($('#trip-mode')); }));
$$('[data-select-day]').forEach(el => el.addEventListener('click', () => { day = Number(el.dataset.selectDay); renderTrip(); }));
$$('[data-trip-tab]').forEach(el => el.addEventListener('click', () => { tab = el.dataset.tripTab; renderTrip(); }));
const checkState = read('checks', {});
$$('[data-check-id]').forEach(el => { el.checked = checkState[el.dataset.checkId] === true; el.addEventListener('change', () => { checkState[el.dataset.checkId] = el.checked; write('checks', checkState); }); });
$$('[data-gallery]').forEach(gallery => {
  const slides = $$('figure', gallery); let current = 0;
  const show = () => { slides.forEach((s, i) => { s.hidden = i !== current; }); const count = $('[data-gallery-count]', gallery); if (count) count.textContent = (current + 1) + ' / ' + slides.length; };
  $$('[data-gallery-step]', gallery).forEach(b => b.addEventListener('click', () => { current = (current + Number(b.dataset.galleryStep) + slides.length) % slides.length; show(); })); show();
});
let mapZoom = 1;
function zoomMap(value) { mapZoom = Math.max(.5, Math.min(5, value)); $('#map-image').style.width = (mapZoom * 100) + '%'; $('#map-zoom-label').textContent = Math.round(mapZoom * 100) + '%'; }
$$('[data-map-open]').forEach(b => b.addEventListener('click', () => { const source = $('#' + b.dataset.mapOpen); $('#map-image').src = source.src; $('#map-image').alt = source.alt; zoomMap(1); openDialog($('#map-viewer')); }));
$('#map-zoom-in').addEventListener('click', () => zoomMap(mapZoom * 1.25));
$('#map-zoom-out').addEventListener('click', () => zoomMap(mapZoom / 1.25));
$('#map-fit').addEventListener('click', () => zoomMap(1));
let spoken = null;
$$('[data-speak]').forEach(button => button.addEventListener('click', () => {
  if (!('speechSynthesis' in window)) { message('当前浏览器不支持语音；文字仍可离线阅读。'); return; }
  speechSynthesis.cancel(); if (spoken === button) { spoken = null; message('已停止朗读'); return; }
  const voices = speechSynthesis.getVoices(), lang = button.dataset.lang;
  const voice = voices.find(v => v.localService === true && v.lang.toLowerCase().startsWith(lang.split('-')[0].toLowerCase()));
  if (!voice) { message('设备没有可用的对应语言语音，未声称已朗读。'); return; }
  const u = new SpeechSynthesisUtterance(button.dataset.speak); u.lang = lang; u.voice = voice;
  u.onend = () => { spoken = null; }; u.onerror = () => { spoken = null; message('设备朗读未成功，请查看文字。'); };
  spoken = button; speechSynthesis.speak(u); message('再次点击同一词句可停止朗读');
}));
$$('[data-photo-input]').forEach(input => input.addEventListener('change', () => {
  const file = input.files && input.files[0]; if (!file) return;
  if (!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type) || file.size > 5 * 1024 * 1024) { message('请选择不超过 5 MB 的 PNG、JPEG、WebP 或 GIF 图片。'); input.value = ''; return; }
  const reader = new FileReader(); reader.onload = () => { const result = String(reader.result); const img = $('#sample-' + input.dataset.photoInput); img.onload = () => { img.hidden = false; const saved = write('photo-' + input.dataset.photoInput, result); if (saved) message('参考图已保存在本机，不会上传或变成经过核验的场所图片。'); }; img.onerror = () => message('图片不能解码，未保存。'); img.src = result; }; reader.readAsDataURL(file);
}));
$$('[data-local-sample]').forEach(img => { const value = read('photo-' + img.dataset.localSample, ''); if (typeof value === 'string' && /^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/]+=*$/.test(value) && value.length < 7500000) { img.src = value; img.hidden = false; } });
$('#copy-adjustment').addEventListener('click', async () => { const el = $('#adjust-structured'), value = el.value.trim(); if (!value) { message('先填写希望调整的日期、活动和约束。'); return; } if(value.length > 3000) { message('申请超过 3000 字，请分批调整；内容没有被截断。'); return; } try { await navigator.clipboard.writeText(value); message('已复制调整请求，请回到旅行应用提交；当前手册不会自行改写已确认行程。'); } catch { el.focus(); el.select(); message('此环境不能自动复制，文字已选中，请手动复制后提交。'); } });
// Local structured request editor: never rewrites the approved itinerary DOM/data.
const routeOriginal = $$('[data-day-panel][data-panel="itinerary"]').map((panel, di) => ({
  date: panel.dataset.dayDate, title: panel.dataset.dayTitle,
  stops: $$('.trip-stop', panel).map((stop, si) => ({ key: di + '-' + si, placeId: stop.dataset.stopId, name: stop.dataset.stopName, time: stop.dataset.stopTime, dwell: Number(stop.dataset.stopDwell), transfer: Number(stop.dataset.stopTransfer) }))
}));
const routeStorageKey = 'route-request-' + document.body.dataset.build;
let routeDraft = read(routeStorageKey, null);
const validStop = s => s && typeof s.key === 'string' && s.key.length <= 80 && typeof s.placeId === 'string' && s.placeId.length <= 100 && typeof s.name === 'string' && s.name.length <= 160 && typeof s.time === 'string' && /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(s.time) && Number.isInteger(s.dwell) && s.dwell >= 0 && s.dwell <= 1440 && Number.isInteger(s.transfer) && s.transfer >= 0 && s.transfer <= 1440;
if (!Array.isArray(routeDraft) || routeDraft.length !== routeOriginal.length || routeDraft.some((d, i) => !d || d.date !== routeOriginal[i].date || !Array.isArray(d.stops) || d.stops.length > 20 || !d.stops.every(validStop))) routeDraft = JSON.parse(JSON.stringify(routeOriginal));
let adjustDay = 0;
function buildRequest() {
  const changes = routeDraft.flatMap((d, i) => JSON.stringify(d.stops) === JSON.stringify(routeOriginal[i].stops) ? [] : ['第 ' + (i + 1) + ' 天 ' + d.date + '，请按以下草稿研究并调整：\n' + (d.stops.length ? d.stops.map((s, j) => (j + 1) + '. ' + s.time + ' ' + s.name + '；停留 ' + s.dwell + ' 分钟；前段交通 ' + s.transfer + ' 分钟；' + (s.placeId ? '原地点ID ' + s.placeId : '新增待研究地点')).join('\n') : '删除当天全部原活动，重新提出可行路线。')]);
  const note = $('#adjust-request').value.trim();
  $('#adjust-structured').value = changes.length || note ? [...changes, ...(note ? ['补充要求：' + note] : []), '请保留原硬性约束；重新核查受影响地点、时间、交通、图片与模块引用，生成独立候选版本供我审核，不要直接改动已采用版本。'].join('\n\n') : '';
}
function persistRoute() { write(routeStorageKey, routeDraft); buildRequest(); }
function renderAdjust() {
  const list = $('#adjust-timeline'); list.replaceChildren();
  const d = routeDraft[adjustDay];
  d.stops.forEach((s, i) => {
    const row = document.createElement('article'); row.className = 'card';
    const heading = document.createElement('h4'); heading.textContent = (i + 1) + '. ' + (s.placeId ? '现有地点草稿' : '新增待研究地点'); row.append(heading);
    [['名称', 'name', 'text'], ['抵达时间', 'time', 'time'], ['停留分钟', 'dwell', 'number'], ['前段交通分钟', 'transfer', 'number']].forEach(([labelText, key, type]) => {
      const label = document.createElement('label'), input = document.createElement('input'); label.className = 'editor-field'; label.textContent = labelText; input.type = type; input.value = String(s[key]); input.setAttribute('aria-label', '第' + (i + 1) + '站' + labelText);
      if (type === 'text') input.maxLength = 160; if (type === 'number') { input.min = '0'; input.max = '1440'; input.step = '1'; }
      input.addEventListener('change', () => { const value = type === 'number' ? Number(input.value) : input.value.trim(); const candidate = Object.assign({}, s, { [key]: value }); if (!validStop(candidate) || key === 'name' && !value) { input.value = String(s[key]); message('请填写有效名称、24小时制时间和 0–1440 之间的整数分钟。'); return; } s[key] = value; persistRoute(); }); label.append(input); row.append(label);
    });
    [['↑ 上移', -1], ['↓ 下移', 1]].forEach(([label, delta]) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = label; b.disabled = i + delta < 0 || i + delta >= d.stops.length; b.addEventListener('click', () => { const target = i + delta; [d.stops[i], d.stops[target]] = [d.stops[target], d.stops[i]]; persistRoute(); renderAdjust(); }); row.append(b, document.createTextNode(' ')); });
    const remove = document.createElement('button'); remove.type = 'button'; remove.textContent = '从申请草稿删除'; remove.addEventListener('click', () => { d.stops.splice(i, 1); persistRoute(); renderAdjust(); }); row.append(remove); list.append(row);
  }); buildRequest();
}
$('#adjust-day').addEventListener('change', e => { adjustDay = Number(e.target.value); renderAdjust(); });
$('#adjust-add').addEventListener('click', () => { const stops = routeDraft[adjustDay].stops; if (stops.length >= 20) { message('每个日期最多 20 个草稿地点，请分批调整。'); return; } stops.push({ key: 'new-' + Date.now().toString(36), placeId: '', name: '请填写待研究地点', time: '12:00', dwell: 60, transfer: 0 }); persistRoute(); renderAdjust(); });
$('#adjust-restore').addEventListener('click', () => { routeDraft[adjustDay] = JSON.parse(JSON.stringify(routeOriginal[adjustDay])); persistRoute(); renderAdjust(); });
$('#adjust-request').addEventListener('input', buildRequest);
renderAdjust();

$('#fx-calculate').addEventListener('click', () => { const amount = Number($('#fx-amount').value), rate = Number($('#fx-rate').value); $('#fx-output').textContent = Number.isFinite(amount) && amount >= 0 && Number.isFinite(rate) && rate > 0 ? (amount * rate).toFixed(2) + '（仅按手动输入汇率估算）' : '请填写有效金额和正汇率'; });

// Local equal-split accounting, integer hundredths and deterministic remainder assignment.
const initial = { revision: 0, members: [{ id: 'm1', name: '成员一' }, { id: 'm2', name: '成员二' }], entries: [] };
let ledger = read('ledger', initial), editing = null, ledgerConflict = false;
if (!ledger || !Array.isArray(ledger.members) || !Array.isArray(ledger.entries) || ledger.members.length > 12 || ledger.entries.length > 1000) ledger = initial;
ledger.members = ledger.members.filter(m => m && /^[A-Za-z0-9_-]{1,80}$/.test(m.id) && typeof m.name === 'string' && m.name.length <= 30);
ledger.entries = ledger.entries.filter(e => e && typeof e.id === 'string' && ['expense','repayment'].includes(e.type) && /^[A-Z]{3}$/.test(e.currency) && Number.isSafeInteger(e.amount) && e.amount > 0 && e.amount <= 10000000000 && typeof e.note === 'string' && e.note.length <= 200 && ledger.members.some(m => m.id === e.payer) && Array.isArray(e.participants) && e.participants.length && e.participants.every(id => ledger.members.some(m => m.id === id)));
const newId = () => 'x' + Date.now().toString(36) + Math.random().toString(36).slice(2, 10);
const nameOf = id => { const m = ledger.members.find(m => m.id === id); return m ? m.name : '未知成员'; };
const el = (tag, text) => { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; return node; };
const action = (text, fn) => { const b = el('button', text); b.type = 'button'; b.addEventListener('click', fn); return b; };
function saveLedger() {
  const latest = read('ledger', null);
  if (ledgerConflict || latest && Number(latest.revision || 0) !== Number(ledger.revision || 0)) { ledgerConflict = true; message('另一窗口已修改记账，本次输入尚未保存。请先复制当前输入，再刷新页面载入最新账目；不会覆盖另一窗口。'); return false; }
  const oldRevision = Number(ledger.revision || 0); ledger.revision = oldRevision + 1;
  if (!write('ledger', ledger)) ledger.revision = oldRevision; renderLedger(); return true;
}
window.addEventListener('storage', event => { if (event.key === namespace + ':ledger') { ledgerConflict = true; message('另一窗口更新了账目；为保留当前输入，请复制后刷新，再继续保存。'); } });
function renderLedger() {
  const members = $('#ledger-members'), payer = $('#ledger-payer'), participants = $('#ledger-participants'), list = $('#ledger-entries'), balances = $('#ledger-balances');
  [members, payer, participants, list, balances].forEach(x => x.replaceChildren());
  ledger.members.forEach(m => {
    const row = el('div'); row.className = 'member-row'; const input = el('input'); input.value = m.name; input.maxLength = 30; input.setAttribute('aria-label', '成员姓名');
    row.append(input, action('改名', () => { if (input.value.trim()) { m.name = input.value.trim(); saveLedger(); } })); members.append(row);
    const option = el('option', m.name); option.value = m.id; payer.append(option);
    const label = el('label'), box = el('input'); box.type = 'checkbox'; box.value = m.id; box.checked = true; label.append(box, document.createTextNode(m.name)); participants.append(label);
  });
  const totals = {}, currencies = {};
  ledger.entries.forEach(e => {
    if (!currencies[e.currency]) currencies[e.currency] = Object.fromEntries(ledger.members.map(m => [m.id, 0])); const net = currencies[e.currency];
    if (e.type === 'repayment') { net[e.payer] += e.amount; net[e.participants[0]] -= e.amount; }
    else { totals[e.currency] = (totals[e.currency] || 0) + e.amount; const ids = [...new Set(e.participants)].sort(); net[e.payer] += e.amount; const base = Math.floor(e.amount / ids.length), remainder = e.amount % ids.length; ids.forEach((id, i) => { net[id] -= base + (i < remainder ? 1 : 0); }); }
    const row = el('article'); row.className = 'ledger-entry'; row.append(el('p', (e.type === 'repayment' ? '还款记录' : e.note) + ' · ' + e.currency + ' ' + (e.amount / 100).toFixed(2) + ' · ' + nameOf(e.payer)));
    if (e.type === 'expense') row.append(action('编辑', () => { editing = e.id; $('#ledger-note').value = e.note; $('#ledger-amount').value = (e.amount / 100).toFixed(2); $('#ledger-currency').value = e.currency; payer.value = e.payer; $$('input', participants).forEach(x => { x.checked = e.participants.includes(x.value); }); $('#ledger-save').textContent = '保存修改'; }));
    row.append(action(e.type === 'repayment' ? '撤销还款记录' : '删除', () => { ledger.entries = ledger.entries.filter(x => x.id !== e.id); saveLedger(); })); list.append(row);
  });
  Object.entries(currencies).forEach(([currency, net]) => {
    balances.append(el('h4', currency + ' · 消费总计 ' + ((totals[currency] || 0) / 100).toFixed(2)));
    ledger.members.forEach(m => balances.append(el('p', m.name + '：' + (net[m.id] >= 0 ? '应收 ' : '应付 ') + (Math.abs(net[m.id]) / 100).toFixed(2))));
    const debt = ledger.members.map(m => ({ id: m.id, n: -net[m.id] })).filter(m => m.n > 0), credit = ledger.members.map(m => ({ id: m.id, n: net[m.id] })).filter(m => m.n > 0);
    let i = 0, j = 0;
    while (i < debt.length && j < credit.length) { const d = debt[i], c = credit[j], amount = Math.min(d.n, c.n), from = d.id, to = c.id;
      const row = el('div', nameOf(from) + ' → ' + nameOf(to) + ' ' + currency + ' ' + (amount / 100).toFixed(2));
      const snapshot = JSON.stringify(ledger.entries.map(e => [e.id,e.amount,e.payer,e.participants])); let hash = 2166136261; for (let k = 0; k < snapshot.length; k++) hash = Math.imul(hash ^ snapshot.charCodeAt(k), 16777619); const repaymentId = 'repay_' + currency + '_' + from + '_' + to + '_' + amount + '_' + (hash >>> 0).toString(36);
      row.append(action('已实际支付，登记', () => { if (!ledger.entries.some(e => e.id === repaymentId)) ledger.entries.push({ id: repaymentId, type: 'repayment', currency, amount, payer: from, participants: [to], note: '仅登记已实际完成的还款，没有转账功能' }); saveLedger(); })); balances.append(row);
      d.n -= amount; c.n -= amount; if (!d.n) i++; if (!c.n) j++;
    }
  });
}
$('#member-add').addEventListener('click', () => { const input = $('#member-name'), name = input.value.trim(); if (!name || ledger.members.length >= 12) { message('请填写姓名；最多 12 名成员。'); return; } ledger.members.push({ id: newId(), name: name.slice(0, 30) }); if (saveLedger()) input.value = ''; });
$('#ledger-save').addEventListener('click', () => {
  const raw = $('#ledger-amount').value, currency = $('#ledger-currency').value.trim().toUpperCase(), note = $('#ledger-note').value.trim(), payer = $('#ledger-payer').value, participants = $$('input:checked', $('#ledger-participants')).map(x => x.value);
  if (!/^\d{1,8}(?:\.\d{1,2})?$/.test(raw) || !/^[A-Z]{3}$/.test(currency) || !note || !payer || !participants.length || ledger.entries.length >= 1000) { message('请填写用途、正金额、三位币种、付款人和至少一名分摊成员。'); return; }
  const parts = raw.split('.'), amount = Number(parts[0]) * 100 + Number((parts[1] || '').padEnd(2, '0'));
  if (!Number.isSafeInteger(amount) || amount <= 0) { message('金额必须大于零'); return; }
  const entry = { id: editing || newId(), type: 'expense', currency, amount, payer, participants, note: note.slice(0, 200) };
  if (editing) ledger.entries = ledger.entries.map(e => e.id === editing ? entry : e); else ledger.entries.push(entry);
  if (saveLedger()) { editing = null; $('#ledger-save').textContent = '记录支出'; $('#ledger-amount').value = ''; $('#ledger-note').value = ''; }
});
$('#ledger-cancel').addEventListener('click', () => { editing = null; $('#ledger-save').textContent = '记录支出'; $('#ledger-amount').value = ''; $('#ledger-note').value = ''; renderLedger(); });
renderLedger(); renderTrip();
})();`;
